server.port=8080
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${SSL_PASSWORD}
server.ssl.key-alias=tomcat
# Zeigt genau, warum Requests erlaubt/blocked werden
logging.level.org.springframework.security=DEBUG

# Für WebSocket Handshake / Mapping
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.web=INFO